import { Career } from "./career";

/** 
 @interface Report A report generated by an AI that gives a list of careers
 @member {Career[]} a list of careers given by the AI
*/
export interface Report{
    careers : Career[]
}